name: 'Verify an NPM release'
description: 'Fetches a package from NPM and does some basic smoke tests'

inputs:
  npm-package:
    description: 'NPM Package'
    required: true
    default: '@terminai/cli@latest'
  npm-registry-url:
    description: 'NPM Registry URL'
    required: true
  npm-registry-scope:
    description: 'NPM Registry Scope'
    required: true
  expected-version:
    description: 'Expected version'
    required: true
  gemini_api_key:
    description: '(Legacy) API key for integration tests; unused in Phase 1.'
    required: false
  github-token:
    description: 'The GitHub token for accessing private repos if needed.'
    required: true
  working-directory:
    description: 'The working directory to run the tests in.'
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: '📝 Print Inputs'
      shell: 'bash'
      env:
        JSON_INPUTS: '${{ toJSON(inputs) }}'
      run: 'echo "$JSON_INPUTS"'

    - name: 'setup node'
      uses: 'actions/setup-node@v4'
      with:
        node-version: '20'

    - name: 'configure .npmrc'
      uses: './.github/actions/setup-npmrc'
      with:
        github-token: '${{ inputs.github-token }}'

    - name: 'Clear npm cache'
      shell: 'bash'
      run: 'npm cache clean --force'

    - name: 'Install from NPM'
      uses: 'nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08' # ratchet:nick-fields/retry@v3
      with:
        timeout_seconds: 900
        retry_wait_seconds: 30
        max_attempts: 10
        command: |-
          cd ${{ inputs.working-directory }}
          npm install --prefer-online --no-cache -g "${{ inputs.npm-package }}"

    - name: 'Smoke test - NPM Install'
      shell: 'bash'
      working-directory: '${{ inputs.working-directory }}'
      run: |-
        terminai_version=$(terminai --version)
        if [ "$terminai_version" != "${{ inputs.expected-version }}" ]; then
          echo "❌ NPM Version mismatch: Got $terminai_version from ${{ inputs.npm-package }}, expected ${{ inputs.expected-version }}"
          exit 1
        fi
        echo "✅ terminai --version: $terminai_version"

    - name: 'Clear npm cache'
      shell: 'bash'
      run: 'npm cache clean --force'

    - name: 'Smoke test - NPX Run'
      shell: 'bash'
      working-directory: '${{ inputs.working-directory }}'
      run: |-
        terminai_version=$(npx --prefer-online --package "${{ inputs.npm-package }}" terminai --version)
        if [ "$terminai_version" != "${{ inputs.expected-version }}" ]; then
          echo "❌ NPX Run Version mismatch: Got $terminai_version from ${{ inputs.npm-package }}, expected ${{ inputs.expected-version }}"
          exit 1
        fi
        echo "✅ npx terminai --version: $terminai_version"
