name: 'Run Tests'
description: 'Runs the preflight checks including build, lint, typecheck, and tests.'

inputs:
  gemini_api_key:
    description: '(Legacy) API key for integration tests; unused in Phase 1.'
    required: false
  working-directory:
    description: 'The working directory to run the tests in.'
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: '📝 Print Inputs'
      shell: 'bash'
      env:
        JSON_INPUTS: '${{ toJSON(inputs) }}'
      run: 'echo "$JSON_INPUTS"'

    - name: 'Run Tests'
      working-directory: '${{ inputs.working-directory }}'
      run: |-
        echo "::group::Build"
        npm run build
        echo "::endgroup::"
        echo "::group::Typecheck"
        npm run typecheck
        echo "::endgroup::"
        echo "::group::Lint"
        npm run lint:ci
        echo "::endgroup::"
        echo "::group::Unit Tests"
        npm run test:ci
        echo "::endgroup::"
      shell: 'bash'
